### ISSUE TITLE
'GSplatLoader' object has no attribute 'opacities'

### ISSUE THREAD

**Issue by MrHenderson6** [chengine/safer-splat#4]
File "/home/WHH/safer-splat-master/visualize.py", line 80, in <module>
    opacities = gsplat.opacities[mask]
                ^^^^^^^^^^^^^^^^
AttributeError: 'GSplatLoader' object has no attribute 'opacities'
ERROR conda.cli.main_run:execute(125): `conda run python /home/WHH/safer-splat-master/visualize.py` failed. (See above for error)

**Comment by chengine** [comment]
Fixed.

**Comment by MrHenderson6** [comment]
Thank you, this issue has been fixed, but there are still some other problems. 
First, should there be an underscore before add_gaussian_splats at line 85 in visualize.py? 
Second, there is a new error reporting that the matrix is not positive definite.
Traceback (most recent call last):
  File "/home/WHH/safer-splat-master/visualize.py", line 85, in <module>
    server.scene._add_gaussian_splats(
  File "/home/WHH/.conda/envs/safer-splat/lib/python3.11/site-packages/viser/_scene_api.py", line 974, in _add_gaussian_splats
    onp.linalg.cholesky(covariances.astype(onp.float64) + onp.ones(3) * 1e-7)
  File "/home/WHH/.conda/envs/safer-splat/lib/python3.11/site-packages/numpy/linalg/_linalg.py", line 839, in cholesky
    r = gufunc(a, signature=signature)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/WHH/.conda/envs/safer-splat/lib/python3.11/site-packages/numpy/linalg/_linalg.py", line 107, in _raise_linalgerror_nonposdef
    raise LinAlgError("Matrix is not positive definite")
numpy.linalg.LinAlgError: Matrix is not positive definite

**Comment by MrHenderson6** [comment]
Thank you, this issue has been fixed, but there are still some other problems.
First, should there be an underscore before add_gaussian_splats at line 85 in visualize.py?
Second, there is a new error reporting that the matrix is not positive definite.
Traceback (most recent call last):
File "/home/WHH/safer-splat-master/visualize.py", line 85, in
server.scene._add_gaussian_splats(
File "/home/WHH/.conda/envs/safer-splat/lib/python3.11/site-packages/viser/_scene_api.py", line 974, in _add_gaussian_splats
onp.linalg.cholesky(covariances.astype(onp.float64) + onp.ones(3) * 1e-7)
File "/home/WHH/.conda/envs/safer-splat/lib/python3.11/site-packages/numpy/linalg/_linalg.py", line 839, in cholesky
r = gufunc(a, signature=signature)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/WHH/.conda/envs/safer-splat/lib/python3.11/site-packages/numpy/linalg/_linalg.py", line 107, in _raise_linalgerror_nonposdef
raise LinAlgError("Matrix is not positive definite")
numpy.linalg.LinAlgError: Matrix is not positive definite

**Comment by chengine** [comment]
Yes, this is expected behavior. As stated in the comments right above that line, you need to update your [viser](https://github.com/nerfstudio-project/viser) package to the latest. The source code for `add_gaussian_splats` is [here](https://viser.studio/main/_modules/viser/_scene_api/#SceneApi.add_gaussian_splats), which only exists for recent versions of viser. The one that comes prepackaged with nerfstudio is of an older version.

**Comment by MrHenderson6** [comment]
Thanks. 
In visualize.py, the function `save_mesh` is used at line 100, but the parameters `bounds` and `res` don't seem to be declared in gsplat_utils.py.

**Comment by chengine** [comment]
Sorry, I should have tested this more thoroughly. Everything should be working now. You will need to pull to get the latest changes. You should see something like the following if you generate trajectories on `stonehenge`. Let me know if it works for you!

![Image](https://github.com/user-attachments/assets/bdc1fc66-7f4a-4ec9-a865-ab7524bb7133)

**Comment by MrHenderson6** [comment]
![Image](https://github.com/user-attachments/assets/a4f63e1d-14da-4292-b1a6-c5cebc41bdc7)
Thank you very much! It runs perfectly now! 
Since I'm a beginner, I still have a few questions. What do the parameters in lines 41-44 of run.y mean? I have trained my own GSplat scene using NS. How should I set parameters like the start and goal if I want to plan in my own scene?

**Comment by chengine** [comment]
Lines 41-44 simply generates a set of circularly (with some up and down in the z height) distributed start and goal points. I would look at lines 101-104, where I specifically set the start (`x`) and the goal (`goal`), and replace them with your values. Since you have your own scene, I would highly recommend you first visualize the GSplat with some software that has a grid to understand the scale of the scene. Something simple you can try is to take a subset of the training poses and set them as your start and goal. However, you need to pay attention here, as Nerfstudio transforms your poses to lie within some unit box oriented in some particular direction. Therefore, your GSplat will not live in the same frame as where your data came from. The configurations chosen in the paper live in the Nerfstudio frame. You can look within the directory where your model weights reside; there should be a file called `dataparser_transforms` that contains the scaling and 6DoF pose that converts from the training frame to the data frame. If you do want to plan in the data frame, you would have to undo this transformation. Some semblance of this already shows up in the function `create_gs_mesh`.
